import Link from "next/link";
import { getSignedInUser } from "@/lib/auth";
import { listCreditPackages } from "@/lib/payment-primitives";

export const dynamic = "force-dynamic";

const tools = [
  ["✦", "Career roadmaps", "A practical 90-day plan, with weekly actions and measurable outcomes."],
  ["▤", "ATS resume drafts", "Build a clear, readable draft from your own experience—without invented credentials."],
  ["in", "LinkedIn writing", "Explore headline options and an About section tailored to your goals."],
  ["◎", "STAR interview practice", "Get specific feedback on Situation, Task, Action, and Result."],
];
if ((process.env.CAREERONESTOP_USER_ID && process.env.CAREERONESTOP_API_TOKEN) || process.env.GEMINI_API_KEY) {
  tools.push(["$", "General salary estimates", "Compare published U.S. wage data or opt into cited AI-assisted web research for other locations."]);
}

const courses = [
  ["Leadership", "Global Remote Leadership", "Asynchronous collaboration, outcome-based KPIs, and clear documentation."],
  ["Cloud strategy", "FinOps & Cloud Cost Optimization", "Resource visibility, ownership, right-sizing, and continuous review."],
  ["Artificial intelligence", "Applied AI for Knowledge Work", "Use AI responsibly for drafting and analysis, with human review."],
  ["Global operations", "Global Contracting and Remote Work", "Know what to clarify about cross-border roles and contracts."],
];

export default async function Home() {
  const [user] = await Promise.all([getSignedInUser()]);
  const packages = listCreditPackages();
  const dashboard = user ? "/dashboard" : "/sign-up";
  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-5 sm:px-8">
      <header className="sticky top-3 z-20 mb-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-700/70 bg-slate-950/90 px-4 py-3 shadow-xl backdrop-blur-xl sm:px-6">
        <Link href="/" className="flex items-center gap-3 text-lg font-black tracking-tight"><span className="grid size-9 place-items-center rounded-xl gradient-bg text-sm">CB</span>CareerBoost</Link>
        <nav aria-label="Main navigation" className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-slate-300"><a href="#tools" className="hidden hover:text-white sm:inline">Tools</a><a href="#courses" className="hidden hover:text-white sm:inline">Courses</a><a href="#pricing" className="hidden hover:text-white sm:inline">Pricing</a><Link href="/privacy" className="hidden hover:text-white sm:inline">Privacy</Link>{user ? <Link href="/dashboard" className="gradient-bg rounded-xl px-4 py-2 font-bold text-white">Candidate hub</Link> : <><Link href="/sign-in" className="hover:text-white">Sign in</Link><Link href="/sign-up" className="gradient-bg rounded-xl px-4 py-2 font-bold text-white">Get started</Link></>}</nav>
      </header>

      <section className="relative isolate overflow-hidden rounded-[2rem] border border-slate-700/70 bg-slate-900/70 px-6 py-14 shadow-2xl sm:px-12 sm:py-20">
        <div aria-hidden="true" className="pointer-events-none absolute -right-24 -top-24 -z-10 size-[32rem] rounded-full bg-indigo-500/20 blur-3xl"/><div aria-hidden="true" className="pointer-events-none absolute -bottom-48 left-1/3 -z-10 size-[28rem] rounded-full bg-cyan-500/10 blur-3xl"/>
        <div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-indigo-300/25 bg-indigo-400/10 px-3 py-1.5 text-xs font-semibold tracking-wide text-indigo-200"><span className="size-1.5 rounded-full bg-cyan-300"/>Career tools for work beyond borders</span><h1 className="mt-6 text-4xl font-black leading-tight tracking-tight sm:text-6xl">Your next career move, <span className="gradient-text">with a clearer plan.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Bring your experience into focus, practise your professional story, and explore practical next steps with AI-assisted tools that keep your account and records in your control.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={dashboard} className="gradient-bg rounded-xl px-6 py-3.5 text-sm font-bold shadow-lg shadow-indigo-950/50">{user ? "Open candidate hub" : "Create your account"}<span aria-hidden="true" className="ml-2">→</span></Link><a href="#tools" className="rounded-xl border border-slate-600 bg-slate-950/40 px-6 py-3.5 text-sm font-semibold text-slate-100">Explore the tools</a></div><p className="mt-5 max-w-2xl text-xs leading-5 text-slate-400">AI suggestions can be wrong. Check every claim and employment term yourself. CareerBoost does not promise jobs, salaries, or accredited qualifications.</p></div>
        <div className="mt-12 grid gap-3 border-t border-slate-700/70 pt-6 sm:grid-cols-3"><div><p className="font-bold text-white">Your profile stays yours</p><p className="mt-1 text-xs leading-5 text-slate-400">Private account data and authenticated access controls.</p></div><div><p className="font-bold text-white">Clear costs before you act</p><p className="mt-1 text-xs leading-5 text-slate-400">See each tool or course cost before using credits.</p></div><div><p className="font-bold text-white">Human-reviewed by design</p><p className="mt-1 text-xs leading-5 text-slate-400">Review drafts and make the final call on your career.</p></div></div>
      </section>

      <section id="tools" className="scroll-mt-28 py-16"><div className="mb-7 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Career studio</p><h2 className="mt-2 text-3xl font-extrabold">Useful support for every next step</h2><p className="mt-3 text-sm leading-6 text-slate-400">Start with your goals and experience. CareerBoost helps you turn them into focused drafts and practice.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tools.map(([icon,title,description],index)=><article key={title} className="glass-card rounded-2xl p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl border border-indigo-300/20 bg-indigo-400/10 font-bold text-indigo-200">{icon}</span><span className="text-xs font-bold text-slate-600">0{index+1}</span></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></article>)}</div></section>

      <section id="how-it-works" className="scroll-mt-28 rounded-3xl border border-slate-700/60 bg-slate-950/45 p-6 sm:p-9"><div className="grid gap-8 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">A simple start</p><h2 className="mt-2 text-3xl font-extrabold">From experience to action</h2><p className="mt-3 text-sm leading-6 text-slate-400">A few clear steps help you get useful output without losing sight of what is yours to decide.</p><Link href={dashboard} className="mt-6 inline-flex rounded-xl border border-indigo-300/30 px-4 py-3 text-sm font-semibold text-indigo-100 hover:bg-indigo-400/10">{user ? "Continue to your hub" : "Start with your profile"} →</Link></div><ol className="grid gap-3 sm:grid-cols-3">{[["01","Set your direction","Add your target role, region, skills, and experience."],["02","Choose a tool","Create a roadmap, resume draft, LinkedIn text, or interview feedback."],["03","Review and refine","Check every detail, then export or copy what you need."]].map(([n,title,body])=><li key={n} className="glass-card rounded-2xl p-5"><span className="text-xs font-black text-cyan-300">{n}</span><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{body}</p></li>)}</ol></div></section>

      <section id="courses" className="scroll-mt-28 py-16"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Learning library</p><h2 className="mt-2 text-3xl font-extrabold">Short, practical courses</h2><p className="mt-2 text-sm text-slate-400">Lessons and quizzes are available in your candidate hub.</p></div><Link href={dashboard} className="text-sm font-semibold text-indigo-200 underline decoration-indigo-400/40 underline-offset-4">Browse in your hub →</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{courses.map(([category,title,description])=><article key={title} className="glass-card rounded-2xl p-5"><span className="text-[11px] font-bold uppercase tracking-wide text-amber-300">{category}</span><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></article>)}</div><p className="mt-4 text-xs text-slate-500">Course records document quiz completion. They are not accredited qualifications.</p></section>

      <section id="pricing" className="scroll-mt-28 border-t border-slate-700/60 py-14"><div className="mb-7 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Credits & pricing</p><h2 className="mt-2 text-3xl font-extrabold">Choose a credit pack</h2><p className="mt-2 text-sm text-slate-400">Prices reflect the packs configured by the service operator.</p></div><div className="mx-auto grid max-w-4xl gap-4 sm:grid-cols-3">{packages.map((bundle)=><article key={bundle.id} className="glass-card rounded-2xl p-5 text-center"><h3 className="font-bold">{bundle.label}</h3><p className="mt-3 text-3xl font-black text-amber-200">{bundle.credits}<span className="ml-2 text-sm font-semibold text-slate-400">credits</span></p><p className="mt-2 text-sm text-slate-300">{bundle.amountSubunits ? new Intl.NumberFormat(undefined,{style:"currency",currency:bundle.currency}).format(bundle.amountSubunits/100) : "Price not configured"}</p><p className="mt-2 text-xs text-slate-500">{bundle.amountSubunits ? `Paid securely in ${bundle.currency}` : "Payments are not enabled for this pack yet"}</p></article>)}</div><p className="mt-5 text-center text-xs text-slate-500">Each tool shows its credit cost. Payments are confirmed by Paystack before credits are added.</p></section>

      <footer className="flex flex-wrap justify-between gap-3 border-t border-slate-700/70 py-8 text-xs text-slate-500"><span>CareerBoost · Your next career step</span><div className="flex gap-5"><Link href="/privacy" className="underline">Privacy & data handling</Link><Link href="/sign-up" className="underline">Create account</Link></div></footer>
    </main>
  );
}
