import Link from "next/link";

export default function PrivacyPage() {
  return <main className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-8"><Link href="/" className="text-sm text-indigo-200 underline">← CareerBoost</Link><article className="glass mt-5 rounded-3xl p-6 sm:p-10"><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-bold uppercase tracking-wide text-amber-200">Pre-launch notice · review required</span><h1 className="mt-5 text-3xl font-extrabold">Privacy and data handling</h1><p className="mt-3 text-sm leading-6 text-slate-300">This technical notice describes the current application design. The business owner must replace or approve it as the legally required privacy notice, identify a privacy contact and controller, and confirm lawful processing and cross-border transfer terms before accepting client data.</p>
    <div className="mt-7 space-y-6 text-sm leading-6 text-slate-300">
      <section><h2 className="font-bold text-white">What this app stores</h2><p>Supabase Auth stores email, password hashes and verification state. Candidate profiles store name, LinkedIn URL, target role, region, salary target, languages, nationality/work location, skills, and experience summary. The database also stores credit ledger entries, course completion codes, and Paystack order amount, currency, status, provider reference, and email.</p></section>
      <section><h2 className="font-bold text-white">When data is sent to another provider</h2><p>If you choose a career tool and agree to the on-screen notice, the relevant profile fields or interview answer are sent to the configured Google Gemini API to generate a draft. Interview voice capture is optional and requires separate consent; supported browsers use their speech-recognition service, which may process audio outside CareerBoost. You can type instead, and only the transcript is submitted to Gemini after you separately accept the AI notice. If you request a salary estimate, only your target occupation and location are sent to CareerOneStop for U.S. published wage data, or—if you enable the separate optional consent—to Google Gemini with Google Search for cited general market research. Your profile name and account ID are not sent for these searches. For Google Search grounding, Google says it stores prompts and outputs for 30 days to provide the feature and debug or test its systems. Salary research is shown only in the active session and is not stored in CareerBoost. LinkedIn Save-to-PDF files are parsed locally in your browser and the PDF file itself is not uploaded; extracted profile text is saved only when you submit the profile form. Email addresses, phone numbers, and links are filtered from imported PDFs. Do not submit information you are not authorized to share. Paystack receives email, amount, currency, and an order reference to process a credit purchase. Vercel hosts the app and may process operational request metadata; Supabase hosts identity and database services.</p></section>
      <section><h2 className="font-bold text-white">Security and access</h2><p>Authenticated sessions use Supabase PKCE cookies. Database row-level policies restrict candidate data and credit history to the owner. Server-only credentials perform payments and staff actions. Administrator credit and role changes create an audit record. Payment credits are awarded only after a server-to-server Paystack verification matches the order.</p></section>
      <section><h2 className="font-bold text-white">Retention currently implemented</h2><p>Deleting an account removes the Auth identity and candidate profile, removes course progress, detaches its credit ledger from the identity, and redacts account email from payment orders. Payment references, amounts, currency, and transaction IDs remain for reconciliation. A daily Vercel job is configured to redact failed/expired order email after 30 days and successful order email after 90 days. That schedule only runs after production deployment with <code>CRON_SECRET</code> configured. Database backups may retain data until their backup retention expires.</p><p className="mt-2">These time periods need approval against the business’s statutory, tax, refund, dispute, and data-protection duties. Vercel and Supabase may retain their own platform logs under their plan settings; this app does not control those provider retention periods.</p></section>
      <section><h2 className="font-bold text-white">Your controls</h2><p>Signed-in candidates can download a JSON export from the dashboard and request account deletion there. Deletion may be temporarily blocked while a payment is pending to prevent an uncredited payment. For a stuck deletion or payment, contact the service operator using the support contact that must be published before launch.</p></section>
      <section><h2 className="font-bold text-white">Before production</h2><p>The operator must publish a working privacy contact, terms and refund policy, verify provider data-processing terms and regions, enable database backups and conduct a restore drill, set monitoring/alerting, configure SMTP and auth CAPTCHA, and approve the retention windows. No privacy officer or support address was supplied for this build.</p></section>
    </div></article></main>;
}
